### ISSUE TITLE
fclose() error

### ISSUE THREAD

**Issue by cjwnz** [javanile/php-imap2#52]
Hi, I'd like to report the following error running under PHP 8.0.28:  (xxx represents removed values)

PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, null given in /xxx/php-imap2/javanile/php-imap2/src/Roundcube/ImapClient.php:442
Stack trace:
#0 /xxx/php-imap2/javanile/php-imap2/src/Roundcube/ImapClient.php(442): fclose(NULL)
#1 /xxx/php-imap2/javanile/php-imap2/src/Roundcube/ImapClient.php(1183): Javanile\Imap2\Roundcube\ImapClient->closeSocket()
#2 /xxx/php-imap2/javanile/php-imap2/src/Roundcube/ImapClient.php(1017): Javanile\Imap2\Roundcube\ImapClient->closeConnection()
#3 /xxx/php-imap2/javanile/php-imap2/src/Connection.php(133): Javanile\Imap2\Roundcube\ImapClient->connect('outlook.office3...', 'xxx', 'xxx', Array)
#4 /xxx/php-imap2/javanile/php-imap2/src/Connection.php(76): Javanile\Imap2\Connection->connect()
#5 /xxx/php-imap2/javanile/php-imap2/bootstrap.php(250): Javanile\Imap2\Connection::open('{outlook.office...', 'xxx', 'xxx', 512, 1, Array)

When is next release of php-imap2 expected?

**Comment by timrasche** [comment]
Still there, no pull requests are handling, no response from author. 

sorry but im out. Package will removed from my source list.

**Comment by williamdes** [comment]
Same
I moved to weblex php imap
https://github.com/wdes/mails.wdes.eu/blob/main/tests/php/tests/SendAndReceiveTest.php

**Comment by daza110** [comment]
I have the same issue.

It unfortunate that the dev whats fundung for PHP 8.4 but cant help with this issues.

I have solved my issue by editing the /xxx/php-imap2/javanile/php-imap2/src/Roundcube/ImapClient.php file:

From: 
`

    protected function closeSocket()
    {
        @fclose($this->fp);
        $this->fp = null;
    }
`

To:
`

    protected function closeSocket()
    {
        if (is_resource($this->fp)) {
            @fclose($this->fp);
        }
        $this->fp = null;
    }
`
